---

- hosts: all
  roles:
  - role: common
  - role: docker
  - role: gantsign.golang
    golang_gopath: '$HOME/workspace-go'

- hosts: k8s
  roles: 
  - rancher

- hosts: all
  roles:
  - role: facts